package com.example.siteshield

object CommonRules {
    val blockedHosts = listOf(
        HostPattern.DomainSuffix("doubleclick.net"),
        HostPattern.DomainSuffix("googlesyndication.com"),
        HostPattern.DomainSuffix("googleadservices.com"),
        HostPattern.DomainSuffix("adnxs.com"),
        HostPattern.DomainSuffix("taboola.com"),
        HostPattern.DomainSuffix("outbrain.com"),
        HostPattern.DomainSuffix("popads.net"),
        HostPattern.DomainSuffix("propellerads.com"),
        HostPattern.DomainSuffix("onclickads.net"),
        HostPattern.DomainSuffix("adsterra.com"),
        HostPattern.DomainSuffix("trafficjunky.net"),
        HostPattern.DomainSuffix("mgid.com"),
        HostPattern.DomainSuffix("exosrv.com"),
        HostPattern.DomainSuffix("redirectingat.com"),
    )

    val suspiciousHostTokens = listOf(
        "adserver",
        "ads.",
        "popunder",
        "popup",
        "redirect",
        "interstitial",
        "clicktrack",
        "push-notif",
    )

    val suspiciousUrlTokens = listOf(
        "/ads/",
        "/ad/",
        "/popunder",
        "/popup",
        "/redirect",
        "/interstitial",
        "/clicktrap",
        "/fake-close",
        "/tracking",
        "/track/",
        "/campaign",
        "/promo",
    )

    val domRules = DomCleanupRules(
        suspiciousSelectors = listOf(
            "iframe[src*='doubleclick']",
            "iframe[src*='googlesyndication']",
            "iframe[src*='popads']",
            "iframe[src*='redirect']",
            "[class*='popup']",
            "[class*='popunder']",
            "[id*='popup']",
            "[id*='overlay']",
        ),
        suspiciousClassTokens = listOf(
            "overlay",
            "modal",
            "popup",
            "popunder",
            "interstitial",
            "ad-",
            "ads-",
            "advert",
            "banner",
            "sponsor",
            "redirect",
            "clicktrap",
            "fake-close",
            "subscribe",
            "campaign",
            "promo",
        ),
        suspiciousUrlTokens = listOf(
            "adserver",
            "doubleclick",
            "googlesyndication",
            "googleadservices",
            "taboola",
            "outbrain",
            "popads",
            "propellerads",
            "onclickads",
            "adsterra",
            "redirect",
            "popunder",
            "interstitial",
            "campaign",
            "promo",
        ),
        baitTextTokens = listOf(
            "continue",
            "allow",
            "download",
            "skip",
            "start",
            "open",
            "close",
            "claim",
            "accept",
            "watch now",
            "play now",
        ),
    )
}
